"""empty message

Revision ID: 333031310215
Revises: 
Create Date: 2025-12-10 21:51:59.885092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333031310215'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('province', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.Column('website_url', sa.String(length=200), nullable=True),
    sa.Column('closed_days', sa.String(length=200), nullable=True),
    sa.Column('operating_hours', sa.String(length=200), nullable=False),
    sa.Column('admission_type', sa.Boolean(), nullable=False),
    sa.Column('admission_detail', sa.Text(), nullable=True),
    sa.Column('parking_available', sa.Boolean(), nullable=False),
    sa.Column('parking_capacity', sa.String(length=120), nullable=True),
    sa.Column('parking_fee', sa.String(length=120), nullable=True),
    sa.Column('requires_reservation', sa.Boolean(), nullable=False),
    sa.Column('amenities', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_urls', sa.Text(), nullable=False),
    sa.Column('public_transportation', sa.Text(), nullable=True),
    sa.Column('local_currency_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('festivals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('province', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.Column('website_url', sa.String(length=200), nullable=True),
    sa.Column('closed_days', sa.String(length=200), nullable=True),
    sa.Column('operating_hours', sa.String(length=200), nullable=False),
    sa.Column('admission_type', sa.Boolean(), nullable=False),
    sa.Column('admission_detail', sa.Text(), nullable=True),
    sa.Column('parking_available', sa.Boolean(), nullable=False),
    sa.Column('parking_capacity', sa.String(length=120), nullable=True),
    sa.Column('parking_fee', sa.String(length=120), nullable=True),
    sa.Column('requires_reservation', sa.Boolean(), nullable=False),
    sa.Column('amenities', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_urls', sa.Text(), nullable=False),
    sa.Column('public_transportation', sa.Text(), nullable=True),
    sa.Column('local_currency_available', sa.Boolean(), nullable=False),
    sa.Column('season', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('places',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('province', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.Column('website_url', sa.String(length=200), nullable=True),
    sa.Column('closed_days', sa.String(length=200), nullable=True),
    sa.Column('operating_hours', sa.String(length=200), nullable=False),
    sa.Column('admission_type', sa.Boolean(), nullable=False),
    sa.Column('admission_detail', sa.Text(), nullable=True),
    sa.Column('parking_available', sa.Boolean(), nullable=False),
    sa.Column('parking_capacity', sa.String(length=120), nullable=True),
    sa.Column('parking_fee', sa.String(length=120), nullable=True),
    sa.Column('requires_reservation', sa.Boolean(), nullable=False),
    sa.Column('amenities', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_urls', sa.Text(), nullable=False),
    sa.Column('public_transportation', sa.Text(), nullable=True),
    sa.Column('local_currency_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('userid', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('profile_image', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('userid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('my_travel_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('places_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('festivals_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['festivals_id'], ['festivals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['places_id'], ['places.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('places_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('festivals_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['festivals_id'], ['festivals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['places_id'], ['places.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('wishlist')
    op.drop_table('review')
    op.drop_table('my_travel_log')
    op.drop_table('user')
    op.drop_table('places')
    op.drop_table('festivals')
    op.drop_table('activity')
    # ### end Alembic commands ###
